### ISSUE TITLE
SingleItemWrapper: Meta Robots wird auf noindex, nofollow gesetzt

### ISSUE THREAD

**Issue by JVolke** [plentymarkets/plugin-ceres#1149]
Weil in der PageMetaData per Default der Meta Robots Tag auf noindex und nofollow gesetzt wird, kommt es dazu, das auch in der Artikelansicht der Robots auf noindex und nofollow steht. Hier müsste entweder per Option es dem Nutzer überlassen werden, wie der Wert sein soll oder man sollte den Wert auf all setzen. 

Im Falle einer Option sollte der Default Wert "All" sein.
@plenty-ceres-io

**Comment by felixdausch** [comment]
Hallo @JVolke 
Vielen Dank für den Hinweis. Der Wert wurde auf "ALL" angepasst:
https://github.com/plentymarkets/plugin-ceres/pull/1191
