### ISSUE TITLE
VAT in checkout order details

### ISSUE THREAD

**Issue by mkreusch** [plentymarkets/plugin-ceres#118]
Currently there is a hard encoded 19% VAT in the order details summary (https://github.com/plentymarkets/plugin-ceres/blob/stable/resources/lang/de/Template.properties basketVAT).
This probably should be changed to "VAT" only or dynamically displayed depending on the real tax.

**Comment by Sebsta13** [comment]
Should be fixed in the next releases.

https://github.com/plentymarkets/plugin-ceres/pull/141
