### ISSUE TITLE
Reset password not working

### ISSUE THREAD

**Issue by bnjroos** [plentymarkets/plugin-ceres#155]
When I click on the reset password link on the email, I simply end up on the homepage. Is that normal ?

**Comment by dbohla** [comment]
Hi @bnjroos,

sorry for the delay. This issue was also discussed in our [forum](https://forum.plentymarkets.com/t/passwort-vergessen-ohne-funktion/70362). Could you please check if the issue still exists when changing the port of your email settings to 587?

Best regards
David

**Comment by bnjroos** [comment]
Working, thank you.
