### ISSUE TITLE
[Beta5] OrderPropertyListItem.vue verursacht Fehler im IE 11

### ISSUE THREAD

**Issue by JVolke** [plentymarkets/plugin-ceres#1915]
@plenty-ceres-io 

Im IE 11 kommt es beim Aufruf der SingleItem zu einem Fehler: 

` Mehrere Definitionen einer Eigenschaft sind im strict-Modus nicht zulässig.`

Zeile:                 `domProps: { value: _vm.property.id, value: _vm.property.value },`

Ursache ist anscheinend folgender Part aus der OrderPropertyListItem.vue: 

```
 <input :name="group ? group.id : 'check' + _uid"
                   :id="'check' + _uid"
                   :value="property.id"
                   v-model="property.value"
                   @change="onInputValueChanged(inputType === 'checkbox' ? $event.target.checked : $event.target.value)"
                   class="form-check-input"
                   :type="inputType">
```

**Comment by felixgehrmann** [comment]
Solved in #2130
