### ISSUE TITLE
Categories side menu not rendering anything

### ISSUE THREAD

**Issue by bnjroos** [plentymarkets/plugin-ceres#197]
I have activated the side menu (using the configuration tab of the plugin) in Ceres categories but no list is showing up, it remains empty. Is there a something more to do than activating it in the configuration tab ?

![opera_2017-11-13_14-45-18](https://user-images.githubusercontent.com/12064956/32714618-4a7e8eca-c881-11e7-9a92-9120ec24d044.png)

Thank you in advance,

**Comment by lks-mtzn** [comment]
Hey, sorry for the delayed response. I can't really help you without having access to your system to check it for myself.

**Comment by bnjroos** [comment]
Made it worked, all good.
