### ISSUE TITLE
Verlinkung leitet auf die Login DE Seite weiter obwohl EN vorhanden

### ISSUE THREAD

**Issue by plenty-ceres** [plentymarkets/plugin-ceres#2443]
<p> 
 
 Für weitere Informationen wende dich bitte an das [Forum](https://forum.plentymarkets.com/t/verlinkung-leitet-auf-die-login-de-seite-weiter-obwohl-en-vorhanden-sichtbarkeit-nach-login/610662/7).

**Comment by stentrop** [comment]
PR: https://github.com/plentymarkets/plugin-io/pull/911
