### ISSUE TITLE
Error "Only Variables can be passed by reference"

### ISSUE THREAD

**Issue by zimanji** [plentymarkets/plugin-ceres#3456]
When I open the project, these two lines are marked as Errors:

https://github.com/plentymarkets/plugin-ceres/blob/83a61723bf8016003c75d8a623145ba81151b262/src/Wizard/ShopWizard/DynamicLoaders/ShopWizardDynamicLoader.php#L71

https://github.com/plentymarkets/plugin-ceres/blob/83a61723bf8016003c75d8a623145ba81151b262/src/Wizard/ShopWizard/DynamicLoaders/ShopWizardDynamicLoader.php#L178

**Comment by stentrop** [comment]
https://github.com/plentymarkets/plugin-ceres/pull/3506/
