### ISSUE TITLE
Weniger ItemsPerPage im OwlCarousel der ContainerItemList für Tablets etc.

### ISSUE THREAD

**Issue by lkreimann** [plentymarkets/plugin-ceres#748]
Hallo zusammen, 

derzeit beschäftige ich mich etwas mehr mit den Artikellisten und hab mir das ganze dann auch mal für die verschiedenen "Bildschirmgrößen" angeguckt. Dabei musste ich leider feststellen, dass der letzte Breakpoint (768), der in der Methode `initializeCarousel()` der [`ContainerItemList`](https://github.com/plentymarkets/plugin-ceres/blob/stable/resources/js/src/app/components/containers/ContainerItemList.js) gewählt ist, nicht ganz optimal ist. So sieht die Anzeige des Cross-Selling-Containers/der Artikelliste z. B. auf einem iPad (portrait orientation; 768 x 1024)  aus: 

![grafik](https://user-images.githubusercontent.com/22977266/49566804-305bcd00-f92c-11e8-92db-e8756d971789.png)
Das sieht leider alles etwas gequetscht aus, vor allem ist der Text auf dem Button nicht vollständig lesbar. 

Mein Vorschlag wäre: Ab einem Breakpoint von 768 werden nur 3 Items per page (dies sind derzeit standardmäßig 4), dann ab einem Breakpoint von 992 jeweils 4 (oder mehr) Items nebeneinander angezeigt. 
Zum Vergleich: In der Artikelliste (auf Kategorie-Ebene) werden bei diesem Breakpoint (768) standardmäßig auch nur 3 Artikel nebeneinander angezeigt.

Kümmere mich auch gerne selber darum, wenn gewünscht :)

**Comment by dbohla** [comment]
Hallo @lkreimann 

Ich habe das Issue einmal in die Entwicklung weitergegeben. Wir melden uns zeitnah.

Gruß
David

**Comment by Tim-M-S** [comment]
Hey Lea @lkreimann 

Wenn du magst kannst du dich selber daran versuchen und dann einen Pull-Request an beta stellen. Wir würden uns freuen :)

Beste Grüße
Tim

**Comment by lkreimann** [comment]
Ich versuche mich mal daran :)

**Comment by lkreimann** [comment]
Sollte ich Dateien, die ich beim Build via Gulp generiert habe in meinem PR inkludieren? Betrifft in der Entiwicklungsumgebung sowieso nur `ceres-app.js` & `ceres-app.js.map` (oder?!) - es wurde nur eine kleine Änderung an einer Vue-Komponente vorgenommen.

**Comment by lks-mtzn** [comment]
Du brauchst sie nicht hinzufügen. Da die Dateien bei jedem Commit auf stable und beta neu generiert und commited werden.

**Comment by lkreimann** [comment]
Ok, so hatte ich mir das gedacht. 👍
