### ISSUE TITLE
Config CompanyLogo deprecated?

### ISSUE THREAD

**Issue by Lauflust** [plentymarkets/plugin-ceres#996]
Warum ist diese Einstellung als "veraltet" markiert? 
https://github.com/plentymarkets/plugin-ceres/blob/ef13b34d06960934241ddfc90580e309f81dab57/config.json#L16-L24

Diese wird noch im aktuellen Ceres-Template an 2 Stellen verwendet:

https://github.com/plentymarkets/plugin-ceres/blob/ef13b34d06960934241ddfc90580e309f81dab57/resources/views/Homepage/Homepage.twig#L6-L16

https://github.com/plentymarkets/plugin-ceres/blob/ef13b34d06960934241ddfc90580e309f81dab57/resources/views/PageDesign/Partials/Header/Navigation.twig#L1-L13

Man kann schon einiges per Shop-Builder machen, aber nach meinen wissen geht das nicht mit den Meta-Daten auf der Homepage. Außerdem nutzt nicht jeder den SB und man muss dann nach der Einstellung suchen. ;-)

BTW: Warum wird dort eigentlich noch nach dem alten Webspace überprüft? 
"_('layout/' in companyLogo)_"
Dies sollte mittlerweile total überflüssig sein.

GlückAuf
Daniel

**Comment by felixdausch** [comment]
Hallo @Lauflust,

die beiden Dateien sind ebenfalls veraltet und werden früher oder später ebenfalls entfernt, da Ceres perspektivisch komplett über den ShopBuilder konfiguriert und angepasst werden soll. Aus diesem Grund ist auch die entsprechende Einstellung "veraltet".

Die Prüfung auf den alten Webspace sollte ursprünglich den Wechsel von Callisto auf Ceres erleichtern. Spätestens mit dem EOL des alten Webspace ist diese Prüfung obsolet. Da diese allerdings keine Fehler verursacht, werden wir sie nicht aus diesen veralteten Templates entfernen.

Grüße
Felix

**Comment by Lauflust** [comment]
Dies ist nachvollziehbar, aber dass in den Meta-Daten das Company-Logo nicht per Shopbuilder geändert wird, sehe ich als Problem an!

**Comment by felixdausch** [comment]
Da gebe ich dir Recht. Wir werden das in unserer Planung berücksichtigen.

**Comment by felixdausch** [comment]
Hallo @Lauflust,

wir haben das Thema noch einmal diskutiert und sind zu folgendem Ergebnis gekommen:
https://github.com/plentymarkets/plugin-ceres/pull/1113

- Der Wert in der Plugin-Konfiguration dient als globaler Fallback für alle Seiten, bei denen kein Bild für die Metadaten zur Verfügung steht.
- Das Navigation-Widget verwendet ebenfalls diese Datei solange keine andere Datei am Widget hochgeladen wird. In diesem Fall wird im head der Seite jedoch auch weiterhin das Bild aus der Konfiguration des Plugins verwendet, da im ShopBuilder immer nur Änderungen am jeweiligen Widget und nicht seitenübergreifend vorgenommen werden.
- Bei Artikel- und Kategorieseiten wird das jeweils hinterlegte Bild (der Kategorie oder des Artikels) verwendet, falls vorhanden. Da perspektivisch alle statischen Seiten in Kategorien überführt werden, um mit dem ShopBuilder editierbar zu sein, hat der Benutzer hier alle erdenklichen Möglichkeiten.
